### ISSUE TITLE
Implement cleanup process

### ISSUE THREAD

**Issue by nekrassov01** [nekrassov01/Pasm#2]
## Todo

Deployment and cleanup should be a set, but cleanup is difficult, so I will implement it later.

- [x] SecurityGroup attached to ENI
- [x] NetworkAcl attached to Subnet
- [x] PrefixList attached to RouteTable and SecurityGroup
- [x] UnitTest
- [x] Release
